# ----------------------------------------
# TRANSAKCE:     1 ucet, 2 karty, 20 transakci, prijmy celkem 22000, vydaje 20000, 4 typy plateb, nektere platby uz kategorizovane
# ----------------------------------------
INSERT INTO moria.transactions (id, account_id, card_number, mcc, merchant_name, constant_symbol, specific_symbol, variable_symbol, exchange_rate, foreign_amount, foreign_currency, booking_date, category_id, direction, party_account_number, party_bank_code, party_prefix, party_description, payee_message, payer_message, transaction_fee, transaction_fee_canceled, transaction_type, user_description, amount, currency, value_date, is_category_manually_assigned, original_value, parent_id) VALUES ('ab01', 6666, '3542658921352648', '3181', 'Sportisimo', null, null, null, null, null, null, '2018-03-07 16:51:48', 0, 'OUTGOING', null, null, null, null, null, null, null, null, 'CARD', null, 899.00, 'CZK', '2018-03-09 09:39:48', null, null, null);
INSERT INTO moria.transactions (id, account_id, card_number, mcc, merchant_name, constant_symbol, specific_symbol, variable_symbol, exchange_rate, foreign_amount, foreign_currency, booking_date, category_id, direction, party_account_number, party_bank_code, party_prefix, party_description, payee_message, payer_message, transaction_fee, transaction_fee_canceled, transaction_type, user_description, amount, currency, value_date, is_category_manually_assigned, original_value, parent_id) VALUES ('ab02', 6666, '3542658921352648', '3560', 'Billa', null, null, null, null, null, null, '2018-03-11 22:08:21', 111, 'OUTGOING', null, null, null, null, null, null, null, null, 'CARD', null, 1521.00, 'CZK', '2018-03-12 07:29:57', true, null, null);
INSERT INTO moria.transactions (id, account_id, card_number, mcc, merchant_name, constant_symbol, specific_symbol, variable_symbol, exchange_rate, foreign_amount, foreign_currency, booking_date, category_id, direction, party_account_number, party_bank_code, party_prefix, party_description, payee_message, payer_message, transaction_fee, transaction_fee_canceled, transaction_type, user_description, amount, currency, value_date, is_category_manually_assigned, original_value, parent_id) VALUES ('ab03', 6666, '4562356984521568', '5968', 'Netflix', null, null, null, null, null, null, '2018-03-16 15:58:26', 118, 'OUTGOING', null, null, null, null, null, null, null, null, 'CARD', null, 230.00, 'CZK', '2018-03-17 16:56:02', true, null, null);
INSERT INTO moria.transactions (id, account_id, card_number, mcc, merchant_name, constant_symbol, specific_symbol, variable_symbol, exchange_rate, foreign_amount, foreign_currency, booking_date, category_id, direction, party_account_number, party_bank_code, party_prefix, party_description, payee_message, payer_message, transaction_fee, transaction_fee_canceled, transaction_type, user_description, amount, currency, value_date, is_category_manually_assigned, original_value, parent_id) VALUES ('ab04', 6666, null, null, null, null, null, null, null, null, null, '2018-04-02 11:06:54', 0, 'OUTGOING', '785845484688', '1500', '00000001', 'Hypotecni banka', null, 'splatka hypoteky', null, null, 'MORTGAGE', 'Mesicni splatka hypoteky', 4099.00, 'CZK', '2018-04-04 07:59:42', null, null, null);
INSERT INTO moria.transactions (id, account_id, card_number, mcc, merchant_name, constant_symbol, specific_symbol, variable_symbol, exchange_rate, foreign_amount, foreign_currency, booking_date, category_id, direction, party_account_number, party_bank_code, party_prefix, party_description, payee_message, payer_message, transaction_fee, transaction_fee_canceled, transaction_type, user_description, amount, currency, value_date, is_category_manually_assigned, original_value, parent_id) VALUES ('ab05', 6666, '4562356984521568', '2358', 'Bio Central', null, null, null, null, null, null, '2018-04-07 08:02:19', 124, 'OUTGOING', null, null, null, null, null, null, null, null, 'CARD', null, 260.00, 'CZK', '2018-04-08 00:50:19', true, null, null);
INSERT INTO moria.transactions (id, account_id, card_number, mcc, merchant_name, constant_symbol, specific_symbol, variable_symbol, exchange_rate, foreign_amount, foreign_currency, booking_date, category_id, direction, party_account_number, party_bank_code, party_prefix, party_description, payee_message, payer_message, transaction_fee, transaction_fee_canceled, transaction_type, user_description, amount, currency, value_date, is_category_manually_assigned, original_value, parent_id) VALUES ('ab06', 6666, null, null, null, '4482', '0', '927335598', null, null, null, '2018-05-22 06:25:02', 0, 'OUTGOING', '945171781792', '0200', '00000014', null, null, 'najem', null, null, 'PAYMENT_HOME', 'Muj landlord', 2500.00, 'CZK', '2018-05-25 01:08:14', null, null, null);
INSERT INTO moria.transactions (id, account_id, card_number, mcc, merchant_name, constant_symbol, specific_symbol, variable_symbol, exchange_rate, foreign_amount, foreign_currency, booking_date, category_id, direction, party_account_number, party_bank_code, party_prefix, party_description, payee_message, payer_message, transaction_fee, transaction_fee_canceled, transaction_type, user_description, amount, currency, value_date, is_category_manually_assigned, original_value, parent_id) VALUES ('ab07', 6666, null, null, null, '6771', null, '4457394676', null, null, null, '2018-05-24 01:31:58', 0, 'INCOMING', '191816107239', '0800', '00000000', null, 'pivo patek', null, null, null, 'PAYMENT_HOME', 'amigo', 262.00, 'CZK', '2018-05-25 11:36:46', null, null, null);
INSERT INTO moria.transactions (id, account_id, card_number, mcc, merchant_name, constant_symbol, specific_symbol, variable_symbol, exchange_rate, foreign_amount, foreign_currency, booking_date, category_id, direction, party_account_number, party_bank_code, party_prefix, party_description, payee_message, payer_message, transaction_fee, transaction_fee_canceled, transaction_type, user_description, amount, currency, value_date, is_category_manually_assigned, original_value, parent_id) VALUES ('ab08', 6666, '4562356984521568', '4449', 'Kafekara', null, null, null, null, null, null, '2018-06-03 08:28:58', 115, 'OUTGOING', null, null, null, null, null, null, null, null, 'CARD', null, 55.00, 'CZK', '2018-06-04 08:00:10', true, null, null);
INSERT INTO moria.transactions (id, account_id, card_number, mcc, merchant_name, constant_symbol, specific_symbol, variable_symbol, exchange_rate, foreign_amount, foreign_currency, booking_date, category_id, direction, party_account_number, party_bank_code, party_prefix, party_description, payee_message, payer_message, transaction_fee, transaction_fee_canceled, transaction_type, user_description, amount, currency, value_date, is_category_manually_assigned, original_value, parent_id) VALUES ('ab09', 6666, '3542658921352648', '3110', 'Regiojet', null, null, null, null, null, null, '2018-07-23 16:01:17', 119, 'OUTGOING', null, null, null, 'Regiojet CZ', null, null, null, null, 'CARD', null, 157.00, 'CZK', '2018-07-26 10:15:41', true, null, null);
INSERT INTO moria.transactions (id, account_id, card_number, mcc, merchant_name, constant_symbol, specific_symbol, variable_symbol, exchange_rate, foreign_amount, foreign_currency, booking_date, category_id, direction, party_account_number, party_bank_code, party_prefix, party_description, payee_message, payer_message, transaction_fee, transaction_fee_canceled, transaction_type, user_description, amount, currency, value_date, is_category_manually_assigned, original_value, parent_id) VALUES ('ab10', 6666, null, null, null, '3317', '0', '777', null, null, null, '2018-08-20 18:38:38', 0, 'INCOMING', '45135662294', '0800', '00000000', null, 'za listek do kina', null, null, null, 'PAYMENT_HOME', 'kamoska', 130.00, 'CZK', '2018-08-21 01:21:50', null, null, null);
INSERT INTO moria.transactions (id, account_id, card_number, mcc, merchant_name, constant_symbol, specific_symbol, variable_symbol, exchange_rate, foreign_amount, foreign_currency, booking_date, category_id, direction, party_account_number, party_bank_code, party_prefix, party_description, payee_message, payer_message, transaction_fee, transaction_fee_canceled, transaction_type, user_description, amount, currency, value_date, is_category_manually_assigned, original_value, parent_id) VALUES ('ab11', 6666, null, null, null, '0', '6484975897', '0', null, null, null, '2018-09-26 07:26:21', 0, 'INCOMING', '528827605187', '0800', '12549856', null, null, null, null, null, 'PAYMENT_HOME', null, 83.00, 'CZK', '2018-09-28 03:07:09', null, null, null);
INSERT INTO moria.transactions (id, account_id, card_number, mcc, merchant_name, constant_symbol, specific_symbol, variable_symbol, exchange_rate, foreign_amount, foreign_currency, booking_date, category_id, direction, party_account_number, party_bank_code, party_prefix, party_description, payee_message, payer_message, transaction_fee, transaction_fee_canceled, transaction_type, user_description, amount, currency, value_date, is_category_manually_assigned, original_value, parent_id) VALUES ('ab12', 6666, null, null, null, '7890', null, '201809666', null, null, null, '2018-10-23 10:32:37', 0, 'INCOMING', '5631075535', '0600', '67010000', 'McDonald''s', 'vyplata za 09/2018', null, null, null, 'PAYMENT_HOME', 'Muj zamestanavatel', 17325.00, 'CZK', '2018-10-25 10:32:37', null, null, null);
INSERT INTO moria.transactions (id, account_id, card_number, mcc, merchant_name, constant_symbol, specific_symbol, variable_symbol, exchange_rate, foreign_amount, foreign_currency, booking_date, category_id, direction, party_account_number, party_bank_code, party_prefix, party_description, payee_message, payer_message, transaction_fee, transaction_fee_canceled, transaction_type, user_description, amount, currency, value_date, is_category_manually_assigned, original_value, parent_id) VALUES ('ab13', 6666, '4562356984521568', '7277', 'Burgrarna', null, null, null, null, null, null, '2018-10-24 03:22:06', 0, 'OUTGOING', null, null, null, null, null, null, null, null, 'CARD', null, 249.00, 'CZK', '2018-10-26 04:22:06', null, null, null);
INSERT INTO moria.transactions (id, account_id, card_number, mcc, merchant_name, constant_symbol, specific_symbol, variable_symbol, exchange_rate, foreign_amount, foreign_currency, booking_date, category_id, direction, party_account_number, party_bank_code, party_prefix, party_description, payee_message, payer_message, transaction_fee, transaction_fee_canceled, transaction_type, user_description, amount, currency, value_date, is_category_manually_assigned, original_value, parent_id) VALUES ('ab14', 6666, null, null, null, '0', '5387662130', '201810', null, null, null, '2018-11-06 15:45:44', 0, 'INCOMING', '162978789688', '2700', '00000000', null, 'splatka dluhu', null, null, null, 'PAYMENT_HOME', null, 4200.00, 'CZK', '2018-11-07 17:45:44', null, null, null);
INSERT INTO moria.transactions (id, account_id, card_number, mcc, merchant_name, constant_symbol, specific_symbol, variable_symbol, exchange_rate, foreign_amount, foreign_currency, booking_date, category_id, direction, party_account_number, party_bank_code, party_prefix, party_description, payee_message, payer_message, transaction_fee, transaction_fee_canceled, transaction_type, user_description, amount, currency, value_date, is_category_manually_assigned, original_value, parent_id) VALUES ('ab15', 6666, '4562356984521568', '3560', 'Billa', null, null, null, null, null, null, '2018-11-28 13:26:16', 0, 'OUTGOING', null, null, null, null, null, null, null, null, 'CARD', null, 2392.00, 'CZK', '2018-11-30 11:59:52', null, null, null);
INSERT INTO moria.transactions (id, account_id, card_number, mcc, merchant_name, constant_symbol, specific_symbol, variable_symbol, exchange_rate, foreign_amount, foreign_currency, booking_date, category_id, direction, party_account_number, party_bank_code, party_prefix, party_description, payee_message, payer_message, transaction_fee, transaction_fee_canceled, transaction_type, user_description, amount, currency, value_date, is_category_manually_assigned, original_value, parent_id) VALUES ('ab16', 6666, null, null, null, '0', null, '20190125', null, null, null, '2018-12-31 00:26:57', 0, 'OUTGOING', '770418267290', '3030', '00000000', 'Vodafone', null, 'Platba za vas predrazeny tarif', null, null, 'PAYMENT_HOME', 'Muj operator', 500.00, 'CZK', '2018-12-31 12:26:57', null, null, null);
INSERT INTO moria.transactions (id, account_id, card_number, mcc, merchant_name, constant_symbol, specific_symbol, variable_symbol, exchange_rate, foreign_amount, foreign_currency, booking_date, category_id, direction, party_account_number, party_bank_code, party_prefix, party_description, payee_message, payer_message, transaction_fee, transaction_fee_canceled, transaction_type, user_description, amount, currency, value_date, is_category_manually_assigned, original_value, parent_id) VALUES ('ab17', 6666, '3542658921352648', '4955', 'STEAM STORE', null, null, null, null, null, null, '2019-01-06 18:54:42', 0, 'OUTGOING', null, null, null, null, null, null, null, null, 'CARD', null, 1898.00, 'CZK', '2019-01-06 14:54:42', null, null, null);
INSERT INTO moria.transactions (id, account_id, card_number, mcc, merchant_name, constant_symbol, specific_symbol, variable_symbol, exchange_rate, foreign_amount, foreign_currency, booking_date, category_id, direction, party_account_number, party_bank_code, party_prefix, party_description, payee_message, payer_message, transaction_fee, transaction_fee_canceled, transaction_type, user_description, amount, currency, value_date, is_category_manually_assigned, original_value, parent_id) VALUES ('ab18', 6666, '3542658921352648', '1234', 'CSOB', null, null, null, null, null, null, '2018-03-11 06:42:10', 0, 'OUTGOING', null, null, null, null, null, null, null, null, 'CASH', 'vyber z bankomatu', null, 'CZK', '2019-01-07 11:15:25', null, 5000.00, null);
INSERT INTO moria.transactions (id, account_id, card_number, mcc, merchant_name, constant_symbol, specific_symbol, variable_symbol, exchange_rate, foreign_amount, foreign_currency, booking_date, category_id, direction, party_account_number, party_bank_code, party_prefix, party_description, payee_message, payer_message, transaction_fee, transaction_fee_canceled, transaction_type, user_description, amount, currency, value_date, is_category_manually_assigned, original_value, parent_id) VALUES ('ab19', 6666, null, null, null, '3347', '0', '4848218390', null, null, null, '2019-02-07 09:58:12', 0, 'OUTGOING', '597175768639', '2700', '00236541', null, null, 'jen tak posilam prachy random osobe', null, null, 'PAYMENT_HOME', 'random osoba', 90.00, 'CZK', '2019-02-08 20:03:00', null, null, null);
INSERT INTO moria.transactions (id, account_id, card_number, mcc, merchant_name, constant_symbol, specific_symbol, variable_symbol, exchange_rate, foreign_amount, foreign_currency, booking_date, category_id, direction, party_account_number, party_bank_code, party_prefix, party_description, payee_message, payer_message, transaction_fee, transaction_fee_canceled, transaction_type, user_description, amount, currency, value_date, is_category_manually_assigned, original_value, parent_id) VALUES ('ab20', 6666, '4562356984521568', '4899', 'Spotify', '0', '0', '0', null, null, null, '2019-02-15 21:43:19', 118, 'OUTGOING', null, null, null, null, null, null, null, null, 'CARD', null, 150.00, 'CZK', '2019-02-18 17:24:07', true, null, null);

# ----------------------------------------
# CHILD TRANSAKCE:
# ----------------------------------------
INSERT INTO moria.transactions (id, account_id, card_number, mcc, merchant_name, constant_symbol, specific_symbol, variable_symbol, exchange_rate, foreign_amount, foreign_currency, booking_date, category_id, direction, party_account_number, party_bank_code, party_prefix, party_description, payee_message, payer_message, transaction_fee, transaction_fee_canceled, transaction_type, user_description, amount, currency, value_date, is_category_manually_assigned, original_value, parent_id) VALUES ('057e2615-28f3-4bab-8365-6f2af75aff47', 6666, '3542658921352648', '1234', 'CSOB', null, null, null, null, null, null, '2018-03-11 06:42:10', 117, 'OUTGOING', null, null, null, null, null, null, null, null, 'CASH', 'vyber z bankomatu', 1500.00, 'CZK', '2019-01-07 11:15:25', true, null, 'ab18');
INSERT INTO moria.transactions (id, account_id, card_number, mcc, merchant_name, constant_symbol, specific_symbol, variable_symbol, exchange_rate, foreign_amount, foreign_currency, booking_date, category_id, direction, party_account_number, party_bank_code, party_prefix, party_description, payee_message, payer_message, transaction_fee, transaction_fee_canceled, transaction_type, user_description, amount, currency, value_date, is_category_manually_assigned, original_value, parent_id) VALUES ('541f3871-f885-4ba7-be96-653ab8b86062', 6666, '3542658921352648', '1234', 'CSOB', null, null, null, null, null, null, '2018-03-11 06:42:10', 127, 'OUTGOING', null, null, null, null, null, null, null, null, 'CASH', 'vyber z bankomatu', 1500.00, 'CZK', '2019-01-07 11:15:25', true, null, 'ab18');
INSERT INTO moria.transactions (id, account_id, card_number, mcc, merchant_name, constant_symbol, specific_symbol, variable_symbol, exchange_rate, foreign_amount, foreign_currency, booking_date, category_id, direction, party_account_number, party_bank_code, party_prefix, party_description, payee_message, payer_message, transaction_fee, transaction_fee_canceled, transaction_type, user_description, amount, currency, value_date, is_category_manually_assigned, original_value, parent_id) VALUES ('7bf8c3e6-154e-49d4-a560-6666f184471a', 6666, '3542658921352648', '1234', 'CSOB', null, null, null, null, null, null, '2018-03-11 06:42:10', 130, 'OUTGOING', null, null, null, null, null, null, null, null, 'CASH', 'vyber z bankomatu', 2000.00, 'CZK', '2019-01-07 11:15:25', true, null, 'ab18');
INSERT INTO moria.transactions (id, account_id, card_number, mcc, merchant_name, constant_symbol, specific_symbol, variable_symbol, exchange_rate, foreign_amount, foreign_currency, booking_date, category_id, direction, party_account_number, party_bank_code, party_prefix, party_description, payee_message, payer_message, transaction_fee, transaction_fee_canceled, transaction_type, user_description, amount, currency, value_date, is_category_manually_assigned, original_value, parent_id) VALUES ('b2136312-1d2e-4173-844e-0695710c3eeb', 6666, '3542658921352648', '1234', 'CSOB', null, null, null, null, null, null, '2018-03-11 06:42:10', 0, 'OUTGOING', null, null, null, null, null, null, null, null, 'CASH', 'vyber z bankomatu', 0.00, 'CZK', '2019-01-07 11:15:25', true, null, 'ab18');

# ----------------------------------------
# RULESETY:     kazdy z nich by mel kategorizovat prave jednu platbu
# ----------------------------------------
# zamyslene jako built-in v aplikaci (shodou okolnosti oboji VYDAJE)
INSERT INTO moria.rulesets (id, rule_name, category_id, party_name, direction, transaction_type, value_from, value_to, party_account_prefix, party_account_number, party_bank_code, payer_message, payee_message, constant_symbol, variable_symbol, specific_symbol, booking_time_from, booking_time_to, card_number) VALUES (1, 'Mortgage monthly payments', 128, 'Hypotecni banka', 'OUTGOING', 'MORTGAGE', null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO moria.rulesets (id, rule_name, category_id, party_name, direction, transaction_type, value_from, value_to, party_account_prefix, party_account_number, party_bank_code, payer_message, payee_message, constant_symbol, variable_symbol, specific_symbol, booking_time_from, booking_time_to, card_number) VALUES (2, 'ATM', 131, null, 'OUTGOING', 'CASH', null, null, null, null, null, null, null, null, null, null, null, null, null);
# zamyslene jako uzivatelsky definovane (prvni dva jsou PRIJMY, treti je VYDAJ)
INSERT INTO moria.rulesets (id, rule_name, category_id, party_name, direction, transaction_type, value_from, value_to, party_account_prefix, party_account_number, party_bank_code, payer_message, payee_message, constant_symbol, variable_symbol, specific_symbol, booking_time_from, booking_time_to, card_number) VALUES (3, 'My main income', 11, null, 'INCOMING', 'PAYMENT_HOME', 15000.00, 25000.00, '67010000', '5631075535', '0600', null, null, null, null, null, null, null, null);
INSERT INTO moria.rulesets (id, rule_name, category_id, party_name, direction, transaction_type, value_from, value_to, party_account_prefix, party_account_number, party_bank_code, payer_message, payee_message, constant_symbol, variable_symbol, specific_symbol, booking_time_from, booking_time_to, card_number) VALUES (4, 'My drinking buddy', 17, null, 'INCOMING', 'PAYMENT_HOME', null, null, '00000000', '191816107239', '0800', null, null, null, null, null, null, null, null);
INSERT INTO moria.rulesets (id, rule_name, category_id, party_name, direction, transaction_type, value_from, value_to, party_account_prefix, party_account_number, party_bank_code, payer_message, payee_message, constant_symbol, variable_symbol, specific_symbol, booking_time_from, booking_time_to, card_number) VALUES (5, 'My addiction', 124, 'Steam', 'OUTGOING', 'CARD', null, null, null, null, null, null, null, null, null, null, null, null, null);
#