/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.2).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package moria.server.api;

import java.math.BigDecimal;
import org.threeten.bp.OffsetDateTime;
import moria.server.model.Payment;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2019-02-27T08:59:02.143Z")

@Api(value = "payment", description = "the payment API")
public interface PaymentApi {

    @ApiOperation(value = "Add a new payment", nickname = "addPayment", notes = "", response = Payment.class, tags={ "payment", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = Payment.class),
        @ApiResponse(code = 405, message = "Invalid input") })
    @RequestMapping(value = "/payment",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Payment> addPayment(@ApiParam(value = "Payment object that needs to be added" ,required=true )  @Valid @RequestBody Payment body);


    @ApiOperation(value = "Finds payment by date", nickname = "findPaymentByDate", notes = "", response = Payment.class, responseContainer = "List", tags={ "payment", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = Payment.class, responseContainer = "List"),
        @ApiResponse(code = 400, message = "Invalid value") })
    @RequestMapping(value = "/payment/findByDate",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<Payment>> findPaymentByDate(@NotNull @ApiParam(value = "Datetime from which to load payments", required = true) @Valid @RequestParam(value = "dateFrom", required = true) OffsetDateTime dateFrom,@NotNull @ApiParam(value = "Datetime to which to load payments", required = true) @Valid @RequestParam(value = "dateTo", required = true) OffsetDateTime dateTo,@NotNull @ApiParam(value = "accountId for transactions", required = true) @Valid @RequestParam(value = "accountId", required = true) BigDecimal accountId);


    @ApiOperation(value = "Update payment", nickname = "updatePayment", notes = "", response = Payment.class, tags={ "payment", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = Payment.class),
        @ApiResponse(code = 405, message = "Invalid input") })
    @RequestMapping(value = "/payment",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.PUT)
    ResponseEntity<Payment> updatePayment(@ApiParam(value = "Payment object that needs to be updated" ,required=true )  @Valid @RequestBody Payment body);

}
