// Transactions
export const GET_TRANSACTIONS = 'GET_TRANSACTIONS';
export const TRANSACTIONS_LOADING = 'TRANSACTIONS_LOADING';
export const SET_FILTER = 'SET_FILTER';
export const UPDATE_TRANSACTION_CATEGORY = 'UPDATE_TRANSACTION_CATEGORY';

// Rules
export const GET_RULES = 'GET_RULES';
export const TOGGLE_RULE_MODAL = 'TOGGLE_RULE_MODAL';
export const RULES_LOADING = 'RULES_LOADING';
export const RULE_ADD = 'RULE_ADD';
export const RULE_EDIT = 'RULE_EDIT';
export const RULE_SUBMIT_CREATE = 'RULE_SUBMIT_CREATE';
export const RULE_SUBMIT_UPDATE = 'RULE_SUBMIT_UPDATE';

// Statistics
export const GET_CHART_DATA = 'GET_CHART_DATA';
export const CHART_DATA_LOADING = 'CHART_DATA_LOADING';
