export const GET_CHART_DATA = 'GET_CHART_DATA';
export const CHART_DATA_LOADING = 'CHART_DATA_LOADING';
export const GET_TRANSACTIONS = 'GET_TRANSACTIONS';
export const TRANSACTIONS_LOADING = 'TRANSACTIONS_LOADING';
export const FILTER_TRANSACTIONS = 'FILTER_TRANSACTIONS';
